### PR TITLE
Correct ext filesystems permissions on GNU/Linux.

### PR DESCRIPTION
**Pull request by Jookia**
Writing multiboot to an ext filesystem would consistently fail due to lacking
permissions. This ensures the multibootusb directory is created and has the
same permissions as the .multibootusb directory in home.

It also removes the immutable flag from ldlinux.sys, meaning it can now be
deleted by either root or user rather than neither.

### CODE REVIEW

**Comment by Jookia** [comment]
This pull request incorporates #26 and #27.

**Comment by mbusb** [comment]
Thanks for the contribution. Your idea seems to be good and this resolves lot of unneeded code.

**Comment by Jookia** [comment]
I did a lot of testing and the only downside with this patch series is that you now get administrator prompts - however gksu/kdesu do have features to get the password so if that's really needed the adminCmd script could be modified to cache passwords. This would keep the theme of using system policies.

That said, thanks for the merge! :)

**Comment by mbusb** [comment]
Tested it. But issue with the current pull request is the multiple password
prompt as brought out by you.

I think the correct way of implementing the privilege elevation is to use
polkit and dbus. That is my opinion and I may be wrong.

**Comment by Jookia** [comment]
If you're talking about having a privileged process interacting with an unprivileged GUI then that sounds about right. Having a pipe or socket with some kind of RPC interface would probably be enough to pull this off. Depending if you put the dd code in to it (which would probably work better), it would have to be required that the server wouldn't block and would have support for querying/killing the status of the dd code, which could just be accomplished using a fork and global variable on the privileged side. It'd also need to keep check on whether the unprivileged process is still alive (you don't want to dd if someone's closed multibootusb.)

On the other hand the annoying multiple password prompts seem to be from needing permissions to install syslinux's MBR. Depending on whether a patch can be done to make this optional (perhaps add the ability to write the MBR to a file instead?), I think the leftovers would be things that absolutely require admin privileges such as writing images. Just a thought on what else can be done.

**Pull request merged**
