### PR TITLE
Introduce infrastructure for rewriting boot configs and refreshed

### PR DESCRIPTION
**Pull request by shinji-s**
persistence support for debians.　Applied changes below for
a debian installation.
  * Boot parameters have to be 'persistence' and 'persistence-path'
  rather than 'persistent' and 'persistent-path'.
  * Backing file must be named 'persistence' rather than 'live-rw'
  * Filesystem on the backing file must contain 'persistence.conf'.

(PLEASE NOTE THAT YOU'LL HAVE TO HAVE 'e2fsck' and 'resize2fs'
ready to run. Be careful when downloading binary files as it
seems trojan with the same names are floating around. 
ALSO PLEASE BE AWARE that this change may break compatibility
with older debians.  We may have to adjust tweaking based on
the version of the debian being installed.)
Avoid rewriting of paths starting with '/cdrom/' or '/dev/'.
Try somedir/vmlinuz if somedir/vmlinuz.efi is unavailable.
Check availability of 'e2fsck' and 'resize2fs'.
Added data/tools/persistence.gz that has initialized ext3 file
system that contains 'persistence.conf' file.

### CODE REVIEW

**Comment by mbusb** [comment]
Is there anything planned for this commit? Let me know if this commit is to be merged...

**Comment by shinji-s** [comment]
@mbusb, thank you for your attention.
I'm reviewing this patch by trying various distributions and I still find things to patch like avoiding rewrite of 'init=/linuxrc' to 'init=/multibootusb/{distrodir}/linuxrc', finding pentoo needs 'subdir=/...' to be appended in its grub.cfg, etc. I'll Cc; you as soon as I feel this PR is ready for your review.

**Comment by shinji-s** [comment]
Though there must be bugs still lurking and incompatibilities with previous implementation, I hope now this patch is good enough to be tested by others.
@mbusb Please review. We should decide what to do as we go along about the need to have e2fscck ans resize2fs on windows.

**Comment by shinji-s** [comment]
Please note that I have not tested on Linux yet. You may have more rough ride there.
I plan to do some Linux testing in a couple of days.

**Comment by shinji-s** [comment]
@mbusb 
Please let me know if you want the commits squashed.

**Pull request merged**
