### PR TITLE
Refactor delete_frm_file_list() to keep /EFI

### PR DESCRIPTION
**Pull request by shinji-s**
usefull work (the distro-dir should have been removed by shutil.rmtree()
by the time this function is called) but can potentially remove files that
are not indented for deletion due to wrong path composition. For example
it tries to remove /EFI rather than /multibootusb/{distro-dir}/EFI.

### CODE REVIEW

**Comment by mbusb** [comment]
Delete from file list is required for distros which are installed in the root of USB device. At least we can use this call only for such distros.

**Comment by shinji-s** [comment]
Thanks. Now I see the intent of having that function. I'll retract or fix this PR.
As for /EFI, we may give it a special treatment. However, how are we going to deal
with potential conflicts?(Assume both distro-A and distro-B creates directory /isolinux
for example and are installed. If we remove /isolinux when installating distro-A,
that would break the installation of distro-B.)
Should we keep record of installing a distro requiring root installation and make sure
there is only one of such installation at a time?

**Comment by mbusb** [comment]
For Linux there should not be a problem. Because, only specific distros are
installed in the root. Even then, we can extract isolinux directory to
distro directory and files which are to be in roo can be extracted to root.

For windows, there is no way as of now. All windows files are installed in
the root. So only last installed windows will boot. There are way to
install multiple version. But I am not aware or should do some research.

**Comment by shinji-s** [comment]
I'll ignore conflict avoidance/resolution for now and gave  special treatment for /EFI directory.
Please review.
Can you point me off the top of your head to a distro that triggers drive root installation?

**Comment by shinji-s** [comment]
Now I have an idea that may be better than unconditionally keeping files under /EFI.
Retracting this PR for now.

**Pull request closed without merging**
