### PR TITLE
Apply hack to prevent gfxboot from locking up when booting antiX-17

### PR DESCRIPTION
**Pull request by shinji-s**
via syslinux. Grub booting does not exhibit similar problem.

### CODE REVIEW

**Comment by shinji-s** [comment]
Can anyone tell what is causing the lock up?

**Comment by mbusb** [comment]
It hangs in syslinux due to incompatibility between distro shipped gfx module and mbusb shipped modules. gfs module of syslinux is known for such incompatibilities.

**Comment by shinji-s** [comment]
Will you reconsider merging this PR? Without this, booting antiX via syslinux hangs.
If you too think we have to disable gfxboot in a systematic way than hacking distro by distro, please let me know you do.

**Comment by shinji-s** [comment]
BTW, just commenting out the line would deprive you of ability to make menu selection.

**Comment by mbusb** [comment]
This PR has  already been merged. Regarding the gfx module issue, it happens only for very few distros which want fancy boot menus. So, I think we should leave as it is for now. We will fix this problem as and when user report the issue.

**Comment by shinji-s** [comment]
Sorry if I'm overlooking something but I see that you closed, instead of merged, this PR
and I don't see relevant code block at develop/HEAD.
Anyway please keep this closed and merge another when I create new PR for this fix.

**Comment by shinji-s** [comment]
Thanks.

**Pull request closed without merging**
