### PR TITLE
GUI cleanup and minor fixes

### PR DESCRIPTION
**Pull request by alindt**
Redesigned GUI for improved usability

### CODE REVIEW

**Comment by mbusb** [comment]
Looks refreshing. I hope that your commit doesn't break away the existing
functionality.

I don't have access to PC at the moment. Will merge it as soon as possible.

**Comment by alindt** [comment]
As far as I've tested, the functionality is the same, it's just the UI elements that have been moved around.

The only changes in functionality are minor UI tweaks like:
- the persistency slider only appears when the selected distro supports it
- the disk/ISO information fields only appear after selecting a disk/ISO
- minor bugs with (re)enabling/disabling buttons and other elements

**Comment by mbusb** [comment]
Thanks. Those were already on my to do list.

**Comment by mbusb** [comment]
I was looking at the modified 'ISO Imager' and 'MultiBootUSB' tab again. How about adding **'Step 1', 'Step 2' and 'Step 3'** text on the respective areas to indicate users to follow the procedures?

**Comment by alindt** [comment]
I don't think telling the user the explicit steps is of very much help because it's pretty straightforward.
Any missed steps, if any, should be stated in some sort of information box after the user clicks the min action button (e.g. "Write image").

I, for one, would like to select an ISO first and then deal with inserting the USB disk, for example. Right now this raises errors because the browse_iso() method does way more than it should (is assumes the USB is already inserted). I'm working right now on cleaning up the program logic so as the basic actions ("Select ISO", "Select USB") do just that, and move all the complex logic into the main action button ("Write ISO") methods.

This way, we clean up and we untangle all the logic, so there won't be a need for "steps" to be taken in order.

**Comment by mbusb** [comment]
I agree that **browse_iso()** method has too many thing to handle. Good to know that you are working further to improve program. At my end, I am working on providing UEFI support and likely to commit after few days.

**Pull request merged**
